zoom_integration.settings:
  type: config_object
  label: 'Zoom Settings'
  mapping:
    access_token_uri:
      type: string
      label: 'Zoom Get Access Token URI'
    base_uri:
      type: string
      label: 'Zoom Base URI'
    account_id:
      type: string
      label: 'Account ID'
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
    webhook_verification_token:
      type: string
      label: 'Webhook Verification Token'
    app_client_id:
      type: string
      label: 'App Client ID'
    app_client_secret:
      type: string
      label: 'App Client Secret'
zoom_integration.access_token_settings:
  type: config_object
  label: 'Zoom Access Token Settings'
  mapping:
    access_token:
      type: text
      label: 'Access Token'
    token_type:
      type: string
      label: 'Token Type'
    expires_in:
      type: integer
      label: 'Expires In'
    expires_time:
      type: integer
      label: 'Expires Time'
    scope:
      type: text
      label: 'Scope'
